@startuml


Application -> Crawler : process()

Crawler -> UriCollection : next()
Crawler <-- UriCollection : uri

Crawler -> DataSource : getDocument(uri)
Crawler <-- DataSource : document

Crawler -> EventDispatcher : dispatch(FETCH_DOCUMENT)

Crawler -> UriExtractor : extract(document)
Crawler <-- UriExtractor : uris

Crawler -> UriCollection : add(uris)

@enduml