@startuml


Application -> Crawler : process()

Crawler -> UrlCollection : next()
Crawler <-- UrlCollection : url

Crawler -> HttpClient : get(url)
Crawler <-- HttpClient : document

Crawler -> EventDispatcher : dispatch(PAGE_FOUND)

Crawler -> HtmlParser : findLinks(documents)
Crawler <-- HtmlParser : urls

Crawler -> UrlCollection : add(urls)

@enduml