@startuml


Application -> Crawler : process()

Crawler -> UriCollection : next()
Crawler <-- UriCollection : url

Crawler -> DataSource : get(url)
Crawler <-- DataSource : document

Crawler -> EventDispatcher : dispatch(PAGE_FOUND)

Crawler -> UriExtractor : findLinks(documents)
Crawler <-- UriExtractor : uris

Crawler -> UriCollection : add(uris)

@enduml